<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.interlis.ch/ILIGML-2.0/Dictionaries_V2" targetNamespace="http://www.interlis.ch/ILIGML-2.0/Dictionaries_V2" elementFormDefault="qualified" attributeFormDefault="unqualified"
  xmlns:gml="http://www.opengis.net/gml/3.2"
  xmlns:INTERLIS="http://www.interlis.ch/ILIGML-2.0/INTERLIS"
  xmlns:ili2c="http://www.interlis.ch/ili2c/ILIGML-2.0"
  xmlns:InternationalCodes_V2="http://www.interlis.ch/ILIGML-2.0/InternationalCodes_V2"
  >
<xsd:annotation>
  <xsd:appinfo source="http://www.interlis.ch/ili2c/ili2cversion">5.6.8-e6f7ab6dd5cdba29afc9b24866ecb98c057d82b2</xsd:appinfo>
  <xsd:appinfo source="http://www.interlis.ch/ili2c">
    <ili2c:Model>
      <ili2c:model>Dictionaries_V2</ili2c:model>
      <ili2c:modelVersion>2021-01-06</ili2c:modelVersion>
      <ili2c:modelIssuer>https://models.geo.admin.ch/CH/</ili2c:modelIssuer>
    </ili2c:Model>
  </xsd:appinfo>
</xsd:annotation>
<xsd:import namespace="http://www.opengis.net/gml/3.2"/>
<xsd:import namespace="http://www.interlis.ch/ILIGML-2.0/INTERLIS"/>
<xsd:import namespace="http://www.interlis.ch/ILIGML-2.0/InternationalCodes_V2"/>
<xsd:element name="Entry" type="EntryType" substitutionGroup="gml:AbstractFeature"/>
<xsd:complexType  name="EntryType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureType">
      <xsd:sequence>
        <xsd:element name="Text">
          <xsd:simpleType>
            <xsd:restriction base="xsd:normalizedString">
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:element name="Dictionary" type="DictionaryType" substitutionGroup="gml:AbstractFeature"/>
<xsd:complexType  name="DictionaryType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureType">
      <xsd:sequence>
        <xsd:element name="Language" type="InternationalCodes_V2:LanguageCode_ISO639_1"/>
        <xsd:element name="Entries" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="Entry"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:complexType name="DictionariesMemberType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureMemberType">
      <xsd:sequence>
        <xsd:choice>
          <xsd:element ref="Dictionary"/>
        </xsd:choice>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:element name="Dictionaries" type="DictionariesType" substitutionGroup="gml:AbstractFeature"/>
<xsd:complexType name="DictionariesType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureType">
      <xsd:sequence>
        <xsd:element name="member" type="DictionariesMemberType" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="gml:AggregationAttributeGroup"/>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
</xsd:schema>
